# Generated by Django 4.1.7 on 2023-04-19 02:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_delete_variationmanager_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=cloudinary.models.CloudinaryField(
                blank=True, default=None, max_length=255
            ),
        ),
    ]
