# Generated by Django 4.1.7 on 2023-04-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderproduct", name="variations",),
    ]
