# Generated by Django 4.1.7 on 2023-04-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_orderproduct_variations"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="city",),
        migrations.RemoveField(model_name="order", name="country",),
        migrations.RemoveField(model_name="order", name="order_note",),
        migrations.RemoveField(model_name="order", name="state",),
        migrations.RemoveField(model_name="order", name="tax",),
    ]
