# Generated by Django 4.1.7 on 2023-05-01 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_order_city_remove_order_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="address_line_1",),
        migrations.RemoveField(model_name="order", name="address_line_2",),
        migrations.RemoveField(model_name="order", name="email",),
        migrations.RemoveField(model_name="order", name="first_name",),
        migrations.RemoveField(model_name="order", name="ip",),
        migrations.RemoveField(model_name="order", name="last_name",),
        migrations.RemoveField(model_name="order", name="payment",),
        migrations.RemoveField(model_name="order", name="phone",),
        migrations.RemoveField(model_name="order", name="status",),
        migrations.RemoveField(model_name="orderproduct", name="created_at",),
        migrations.RemoveField(model_name="orderproduct", name="ordered",),
        migrations.RemoveField(model_name="orderproduct", name="payment",),
        migrations.RemoveField(model_name="orderproduct", name="product_price",),
        migrations.RemoveField(model_name="orderproduct", name="updated_at",),
        migrations.RemoveField(model_name="orderproduct", name="user",),
        migrations.DeleteModel(name="Payment",),
    ]
