# Generated by Django 4.1.7 on 2023-05-02 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_address_line_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="is_ordered",),
    ]
